import Header from '../components/Header';
import Footer from '../components/Footer';

const courses = [
  { code: 'BSc IT', title: 'BSc Information Technology', detail: 'Build practical skills in software, networks, and digital systems.', icon: 'fas fa-laptop-code', image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=700&h=450&fit=crop', path: '/course/bsc' },
  { code: 'BSc CS', title: 'BSc Computer Science', detail: 'Explore algorithms, computing theory, and intelligent technologies.', icon: 'fas fa-microchip', image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=700&h=450&fit=crop', path: '/course/bsc' },
  { code: 'BSc Microbiology', title: 'BSc Microbiology', detail: 'Study microorganisms, laboratory science, and applied biology.', icon: 'fas fa-flask', image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=700&h=450&fit=crop', path: '/course/bsc' },
  { code: 'BCA', title: 'Bachelor of Computer Applications', detail: 'Learn software development, databases, and modern computing.', icon: 'fas fa-laptop-code', image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=700&h=450&fit=crop', path: '/course/bca' },
  { code: 'BA', title: 'Bachelor of Arts', detail: 'Explore humanities, society, communication, and creative thought.', icon: 'fas fa-book-open', image: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=700&h=450&fit=crop', path: '/course/ba' },
  { code: 'MBA', title: 'Master of Business Administration', detail: 'Develop confident leaders ready for a changing business world.', icon: 'fas fa-chart-line', image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=700&h=450&fit=crop', path: '/course/mba' },
  { code: 'MCA', title: 'Master of Computer Applications', detail: 'Advance your technical expertise through applied learning.', icon: 'fas fa-microchip', image: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=700&h=450&fit=crop', path: '/course/mca' },
  { code: 'BCom', title: 'Bachelor of Commerce', detail: 'Learn accounting, finance, business, and entrepreneurship.', icon: 'fas fa-calculator', image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=700&h=450&fit=crop', path: '/course/bcom' }
];

const admissionSteps = [
  ['01', 'Explore programmes', 'Compare courses and choose the programme that matches your goals.'],
  ['02', 'Submit your application', 'Complete the online enquiry or application form with your details.'],
  ['03', 'Meet our admissions team', 'Get guidance on eligibility, documents, fees, and the next steps.'],
  ['04', 'Begin your journey', 'Confirm your seat, complete enrolment, and prepare for campus life.']
];

const notices = [
  { date: '15 Sep', title: 'Admissions open for the 2026-27 academic session', type: 'Admissions' },
  { date: '08 Sep', title: 'Internal assessment schedule published', type: 'Examination' },
  { date: '02 Sep', title: 'Scholarship applications are now being accepted', type: 'Student Notice' }
];

const Home = () => (
  <>
    <Header />
    <main>
      <section className="institute-hero" id="home"><div className="container institute-hero-content"><div className="institute-hero-copy"><p className="eyebrow">ABHINOVA INSTITUTE OF HIGHER EDUCATION</p><h1>Learn with purpose.<br /><span>Lead with confidence.</span></h1><p>Where curiosity becomes capability. Abhinova Institute gives students the knowledge, mentorship, and practical experience to shape a better future.</p><div className="hero-buttons"><a href="#courses" className="hero-btn primary-btn">Explore Courses</a><a href="/about" className="hero-btn secondary-btn">Discover Abhinova</a></div><div className="hero-trust"><div className="hero-avatars"><span>AM</span><span>RK</span><span>PS</span><span>+40</span></div><div><strong>★★★★★</strong><span>Trusted by students and families</span></div></div><div className="institute-hero-stats"><div><strong>25+</strong><span>Years of learning</span></div><div><strong>40+</strong><span>Expert faculty</span></div><div><strong>8</strong><span>Career-focused courses</span></div></div></div><div className="institute-hero-image"><img src="https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1000&h=800&fit=crop" alt="Indian students learning together at Abhinova Institute" /><div className="hero-image-note"><i className="fas fa-graduation-cap"></i><span>Shape your<br /><strong>next chapter</strong></span></div></div></div></section>
      <section className="intro-section"><div className="container intro-grid"><div className="intro-image"><img src="https://images.unsplash.com/photo-1756885375569-f04400d99cee?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" alt="Indian students learning together in a classroom" /></div><div className="intro-copy"><p className="eyebrow">WELCOME TO ABHINOVA</p><h2>Education that opens more doors.</h2><p>Abhinova Institute is a student-first learning community where strong academics meet real-world perspective. Our classrooms encourage questions, our faculty recognize individual potential, and our campus gives every learner room to grow.</p><p>From the first lecture to the first career milestone, we stand beside our students with guidance, opportunity, and a culture that celebrates progress.</p><a className="text-link" href="/about">Read our story <i className="fas fa-arrow-right"></i></a></div></div></section>
      <section className="course-section" id="courses"><div className="container"><div className="section-header"><p className="eyebrow">FIND YOUR DIRECTION</p><h2>Popular courses</h2><p>Thoughtfully designed programmes for ambitious learners.</p></div><div className="course-grid">{courses.map((course) => <article className="course-card course-card-with-image" key={course.code}><img src={course.image} alt={`${course.title} students at Abhinova Institute`} /><div className="course-card-body"><h3>{course.title}</h3><p>{course.detail}</p><a href={course.path} aria-label={`View ${course.title}`}><i className="fas fa-arrow-up-right-from-square"></i></a></div></article>)}</div></div></section>
      <section className="why-section"><div className="container why-grid"><div><p className="eyebrow">THE ABHINOVA DIFFERENCE</p><h2>More than a degree.<br /><span>A launchpad for life.</span></h2><p>We pair rigorous teaching with the experiences that help students become thoughtful professionals, inventive problem-solvers, and responsible citizens.</p><a className="hero-btn primary-btn" href="/why-choose-us">Why choose us</a></div><div className="why-list"><div><i className="fas fa-users"></i><span><strong>Mentors who know your name</strong><small>Personal guidance from a faculty that invests in your growth.</small></span></div><div><i className="fas fa-building-columns"></i><span><strong>Learning beyond the classroom</strong><small>Labs, projects, clubs, and industry exposure that make ideas tangible.</small></span></div><div><i className="fas fa-seedling"></i><span><strong>A campus built for confidence</strong><small>Inclusive spaces where every student can find their voice.</small></span></div></div></div></section>
      <section className="principal-section"><div className="container principal-grid"><div className="principal-image"><img src="/assets/image/photo.png" alt="Indian man serving as Principal of Abhinova Institute" /></div><div className="principal-copy"><p className="eyebrow">A MESSAGE FROM OUR PRINCIPAL</p><h2>“Every student carries a possibility worth nurturing.”</h2><p>At Abhinova Institute, we believe education is not only about what students learn, but also about who they become. Our responsibility is to create an environment where curiosity is welcomed, effort is respected, and every young person can move towards a meaningful future.</p><p>We invite you to experience a community that learns together and leads with purpose.</p><strong className='text-white'>Mr. Abishek Yadav</strong><span>Founder, Abhinova Institute</span></div></div></section>
      <section className="notice-section"><div className="container notice-grid"><div className="section-header"><p className="eyebrow">STAY IN THE KNOW</p><h2>Latest notices</h2><p>Important updates from our campus.</p><a className="text-link" href="/contact">View all notices <i className="fas fa-arrow-right"></i></a></div><div className="notice-list">{notices.map((notice) => <article key={notice.title}><time>{notice.date}</time><div><span>{notice.type}</span><h3>{notice.title}</h3></div><i className="fas fa-arrow-up-right-from-square"></i></article>)}</div></div></section>
      <section className="admission-section"><div className="container"><div className="section-header"><p className="eyebrow">YOUR NEXT STEP</p><h2>Admission process</h2><p>A clear path from your first enquiry to your first day on campus.</p></div><div className="admission-grid">{admissionSteps.map(([number, title, description]) => <article className="admission-card" key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div></div></section>
      <section className="events-preview"><div className="container"><div className="section-header"><p className="eyebrow">CAMPUS LIFE</p><h2>Upcoming events</h2><p>Ideas, conversations, and experiences that bring our community together.</p></div><div className="event-mini-grid"><article><img src="https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=700&h=450&fit=crop" alt="Academic conference" /><div><span>18 Oct 2026</span><h3>Annual Academic Conference</h3></div></article><article><img src="https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=700&h=450&fit=crop" alt="Science exhibition" /><div><span>06 Nov 2026</span><h3>Science &amp; Technology Exhibition</h3></div></article><article><img src="https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=700&h=450&fit=crop" alt="Guest lecture" /><div><span>22 Nov 2026</span><h3>Guest Lecture Series</h3></div></article></div><a className="text-link" href="/events">Explore all events <i className="fas fa-arrow-right"></i></a></div></section>
      <section className="reviews-section"><div className="container"><div className="section-header"><p className="eyebrow">STUDENT VOICES</p><h2>Growing together</h2></div><div className="review-grid"><blockquote><div className="stars">★★★★★</div><p>“Abhinova gave me the confidence to turn my interest in technology into a real career path. The faculty always made time for my questions.”</p><strong>Gyan Chand Yadav</strong><br></br><span>BCA, Class of 2021</span></blockquote><blockquote><div className="stars">★★★★★</div><p>“The best part of studying here is the balance between academics and practical experiences. I found my community from the very first semester.”</p><strong>Shivam Mishra</strong><br></br><span>MBA, Class of 2024</span></blockquote><blockquote><div className="stars">★★★★★</div><p>“Our mentors challenged us to think independently. I graduated with knowledge, but also with a clear sense of direction.”</p><strong>Gyan Chand Yadav</strong><br></br><span>MCA, Class of 2025</span></blockquote></div></div></section>
    </main>
    <Footer />
  </>
);

export default Home;
